export const InGameGT = Object.freeze({
  AIR_DROP_LOOTED: "AIR DROP LOOTED.gtzip",

  DEAD_ALIVE_18_TEAMS: "DEAD ALIVE 18 TEAMS.gtzip",

  DEAD_ALIVE: "DEAD ALIVE.gtzip",

  DOMINATION: "DOMINATION.gtzip",

  ELIMINATION: "ELIMINATION.gtzip",

  FIRST_BLOOD: "FIRST BLOOD.gtzip",

  GRENADIER: "GRENADIER.gtzip",

  INGAME_OVERLAY: "INGAME OVERLAY.gtzip",

  MAP_x_DMG: "MAP + DMG.gtzip",

  MAP_x_ELIMS: "MAP + ELIMS.gtzip",

  MAP_x_LONG_ELIM: "MAP + LONG ELIM.gtzip",

  MAP_x_OVERALL_STANDINGS: "MAP + OVERALL STANDINGS.gtzip",

  MATCH__INTRO: "MATCH  INTRO.gtzip",
});
